### ISSUE TITLE
Could not execute query, because the Python bridge has not been initalized. If the issue persists, please open a Github issue.

### ISSUE THREAD

**Issue by PaxonF** [AltimateAI/vscode-dbt-power-user#236]
### Expected behavior

A query is able to be run, or a model is able to be generated when clicking the "Generate model" button in a .yml file.

### Actual behavior

The following error occurs, even after following all setup instructions, including having the correct python interpreter installed, and being able to run dbt commands within the virtualenv.

`Could not execute query, because the Python bridge has not been initalized. If the issue persists, please open a Github issue.`

### Steps To Reproduce

1. Install dbt Power User extension within a dbt environment on MacOS.
2. Create a python virtual environment (In my case, I am using `poetry`)
3. Install dbt using `poetry`.
4. Select the Python interpreter to use your newly created venv
5. Attempt to "Generate model" from .yml file or run a SQL script

### Log output/Screenshots

<img width="464" alt="image" src="https://user-images.githubusercontent.com/25188107/204858993-69c36221-1d48-47de-b2a4-d24fed5fbfb3.png">

### Operating System

Mac OS Monterry

### dbt version

1.3.1

### dbt Adapter

bigquery 1.3.0

### dbt Power User version

0.10.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Is dbt being successfully detected?

Are you getting any other errors?

**Comment by gwenwindflower** [comment]
same issue here, no other errors, same details -- dbt is being detected ✅

**Comment by mdesmet** [comment]
Can you check Help > Toggle Developer Tools and check the console log. 

If possible could you try to create a reproduction repo.

**Comment by mdesmet** [comment]
I actually did the reproduction steps and used poetry and wasn't able to reproduce the issue.

**Comment by gwenwindflower** [comment]
```
workbench.desktop.main.js:820 Could not execute query, because the Python bridge has not been initalized. If the issue persists, please open a Github issue.
onDidChangeNotification @ workbench.desktop.main.js:820
(anonymous) @ workbench.desktop.main.js:820
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
addNotification @ workbench.desktop.main.js:820
notify @ workbench.desktop.main.js:1992
(anonymous) @ workbench.desktop.main.js:1736
_showMessage @ workbench.desktop.main.js:1736
$showMessage @ workbench.desktop.main.js:1736
_doInvokeHandler @ workbench.desktop.main.js:1743
_invokeHandler @ workbench.desktop.main.js:1743
_receiveRequest @ workbench.desktop.main.js:1743
_receiveOneMessage @ workbench.desktop.main.js:1743
(anonymous) @ workbench.desktop.main.js:1743
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:546
_receiveMessage @ workbench.desktop.main.js:546
(anonymous) @ workbench.desktop.main.js:546
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
acceptChunk @ workbench.desktop.main.js:546
(anonymous) @ workbench.desktop.main.js:546
y @ workbench.desktop.main.js:546
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
Show 2 more frames
workbench.desktop.main.js:87 [Extension Host] rejected promise not handled within 1 second: Error: Could not initialize Python bridge
E @ workbench.desktop.main.js:87
$logExtensionHostMessage @ workbench.desktop.main.js:1743
_doInvokeHandler @ workbench.desktop.main.js:1743
_invokeHandler @ workbench.desktop.main.js:1743
_receiveRequest @ workbench.desktop.main.js:1743
_receiveOneMessage @ workbench.desktop.main.js:1743
(anonymous) @ workbench.desktop.main.js:1743
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:546
_receiveMessage @ workbench.desktop.main.js:546
(anonymous) @ workbench.desktop.main.js:546
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
acceptChunk @ workbench.desktop.main.js:546
(anonymous) @ workbench.desktop.main.js:546
y @ workbench.desktop.main.js:546
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
workbench.desktop.main.js:87 [Extension Host] stack trace: Error: Could not initialize Python bridge
    at DBTProject.<anonymous> (/Users/grant/.vscode/extensions/innoverio.vscode-dbt-power-user-0.10.1/dist/extension.js:7520:7)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/grant/.vscode/extensions/innoverio.vscode-dbt-power-user-0.10.1/dist/extension.js:8847:23)
E @ workbench.desktop.main.js:87
$logExtensionHostMessage @ workbench.desktop.main.js:1743
_doInvokeHandler @ workbench.desktop.main.js:1743
_invokeHandler @ workbench.desktop.main.js:1743
_receiveRequest @ workbench.desktop.main.js:1743
_receiveOneMessage @ workbench.desktop.main.js:1743
(anonymous) @ workbench.desktop.main.js:1743
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:546
_receiveMessage @ workbench.desktop.main.js:546
(anonymous) @ workbench.desktop.main.js:546
invoke @ workbench.desktop.main.js:83
deliver @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:83
acceptChunk @ workbench.desktop.main.js:546
(anonymous) @ workbench.desktop.main.js:546
y @ workbench.desktop.main.js:546
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
workbench.desktop.main.js:609   ERR Could not initialize Python bridge: Error: Could not initialize Python bridge
    at DBTProject.<anonymous> (/Users/grant/.vscode/extensions/innoverio.vscode-dbt-power-user-0.10.1/dist/extension.js:7520:7)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/grant/.vscode/extensions/innoverio.vscode-dbt-power-user-0.10.1/dist/extension.js:8847:23)
```
<img width="546" alt="Screenshot 2022-12-06 at 11 45 01" src="https://user-images.githubusercontent.com/91998347/205984205-1335e30d-3580-4378-b290-ab337ccbd77f.png">

Log and screenshot of the console -- will try to setup a repro-repo for you soon! Thanks for checking into this.

**Comment by gwenwindflower** [comment]
(btw I'm not using poetry, just `venv` but i am nonetheless in a virtual environment)

**Comment by mdesmet** [comment]
There are no other logged errors before the `workbench.desktop.main.js:820 Could not execute query, because the Python bridge has not been initalized. If the issue persists, please open a Github issue.`

**Comment by gwenwindflower** [comment]
@mdesmet apologies i haven't had time to spin up a repro repo yet, but hopefully can do that tomorrow.

wanted to offer another question/theory as i've noticed that it throws some earlier errors when initializing the project that i had missed, as i had the project open and running for a long time. the earliest error it seems to throw is that is can't find the profile defined (dbt has no problem running so the profile is definitely available) -- which makes me wonder, is it updated to account for the recent update to dbt core that will check in the project directory first for a `profiles.yml` before looking in `~/.dbt`? that's how i've set this repo up, with the duckdb adapter. so i'm wondering if it's throwing the rest of the errors based on that initial issue?

**Comment by mdesmet** [comment]
I wasn't aware about that change in dbt core. That is probably the reason. I'll do a fix tomorrow.

**Comment by mdesmet** [comment]
Fixed in 0.10.2

Let me know if this fixes the issue.

**Comment by Pierre-Semaan** [comment]
I'm still seeing this, and I'm on v0.10.3. I no longer see the generate models option, and get this error when hitting "cmd" + "enter"

**Comment by Pierre-Semaan** [comment]
Further to my last update, I noticed this error this morning when trying to preview a model's query. Let me know if I should open a new issue, @mdesmet :

2022-12-19 10:48:06.714 [error] ENOPRO: No file system provider found for resource 'query-preview:/Users/myuser/myWork/my-data/models/staging/snowplow/stg_snowplow__events.sql'
    at h.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:616:11207)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async h.U (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:616:22969)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:616:22856
2022-12-19 10:48:17.757 [error] cannot open query-preview:/Users/myuser/myWork/my-data/models/staging/snowplow/stg_snowplow__events.sql. Detail: Could not initialize Python bridge: Error: cannot open query-preview:/Users/myuser/myWork/my-data/models/staging/snowplow/stg_snowplow__events.sql. Detail: Could not initialize Python bridge
    at n.$tryOpenDocument (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2485:77012)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-12-19 10:49:29.180 [error] Unable to read file '/Users/myuser/myWork/my-data/models/staging/snowplow/stg_snowplow__events.sql' (Error: File not modified since): Error: Unable to read file '/Users/myuser/myWork/my-data/models/staging/snowplow/stg_snowplow__events.sql' (Error: File not modified since)
    at h.v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:616:16493)
    at async v.H (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2491:34436)
    at async v.readStream (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2491:34131)
    at async Ms.Ab (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2480:54169)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2491:30190

**Comment by mdesmet** [comment]
Please provide a reproduction repo or exact steps on how to reproduce your issue.

**Comment by Pierre-Semaan** [comment]
I don't have a reproduction repo set up, @mdesmet, but I noticed a couple of things:
- Even though I have a reference to the proper DBT_PROFILES_DIR in my .vscode settings.json, I get an error when starting VSCode that DBT Power User can't find my profile on startup
![image](https://user-images.githubusercontent.com/97063651/208522685-5dbc2b3b-6a4a-47cd-b881-50fceec4c395.png)
- none of my yaml source files offer me that chance to generate a model. The option is non-existent
- hitting command + enter provides the error listed above. 
- I think I have my environment set up properly 
![image](https://user-images.githubusercontent.com/97063651/208523253-340cf532-4d72-4018-8112-26a33bd22697.png)

**Comment by mdesmet** [comment]
You need to fix `Could not find profile named ...` error. How do you set the `DBT_PROFILES_DIR`?

**Comment by Pierre-Semaan** [comment]
It's set inside of my VSCode settings.json file. I don't change anything else inside of VSCode after the error, but if I run "dbt debug --config-dir" in a terminal, I see this: 
![image](https://user-images.githubusercontent.com/97063651/208526493-aca92c6a-98c1-4506-8a36-7b5ab9248beb.png) It seems to be an error with the extension not reading my settings.json?

**Comment by mdesmet** [comment]
I still don't know how you setup DBT_PROFILES_DIR in your settings.json, so I can't say if it should work or not.

**Comment by Pierre-Semaan** [comment]
I have the following in my settings.json. There is a profiles.yml in a profiles directory inside of the folder structure my project is in: 
![image](https://user-images.githubusercontent.com/97063651/208527786-0ff50712-3066-4370-999c-e919dd6e58a0.png)

![image](https://user-images.githubusercontent.com/97063651/208527501-f95854e7-3a89-4482-ab0c-7db63a690c8b.png)
I also tried running "export DBT_PROFILES_DIR=./profiles" and it results in the same output. Running the open command, as displayed, opens the directory that has my profiles.yml file that contains the profile that is named in the profiles.yml file

**Comment by Pierre-Semaan** [comment]
That information is from the extension's marketplace page: https://marketplace.visualstudio.com/items?itemName=innoverio.vscode-dbt-power-user
![image](https://user-images.githubusercontent.com/97063651/208528239-f8ef91bf-cc28-451f-bd44-b139204270eb.png)

My profiles.yml isn't in the root, though - it's in a profiles directory

**Comment by Pierre-Semaan** [comment]
Copied the profiles.yml out to the root directory, and changed the settings.json to be  "DBT_PROFILES_DIR": "." and the error went away on opening VSCode, but I still can't preview a query. 
![image](https://user-images.githubusercontent.com/97063651/208530337-2d5109d6-8944-4b9a-9547-e76d42cc3c0c.png)

**Comment by mdesmet** [comment]
If it's in a fixed directory relative to your dbt project you could set it to `./profiles`. About the other error I'm not sure, it means that the project can't be parsed for some reason.

Maybe try to setup a reproduction repo?

**Comment by Pierre-Semaan** [comment]
It is a fixed directory. And it was causing the error I pasted above
![image](https://user-images.githubusercontent.com/97063651/209142748-ee6e75d9-a3d7-48e0-96af-c76d0f7e61d5.png)
On a whim this morning, I moved the profiles.yml file out to the root directory of the project, changed my setting.json file to use 
"terminal.integrated.env.osx": {
        "DBT_PROFILES_DIR": "."
    },
and closed the project. Reopened the project, and most everything worked. I can now query the model using "cmd + Enter", but I still don't have the option to generate a model from the source definition. 
![image](https://user-images.githubusercontent.com/97063651/209158303-c3be6e48-2b5e-48d7-a28e-e6431e3e44eb.png)
Moving the profiles.yml out of the root, leaving it in the projects folder in the root directory, and changing the settings.json back leads to the error.    
"terminal.integrated.env.osx": {
        "DBT_PROFILES_DIR": "./profiles"
    },
I can use that directory with no issue in the dbt core command line if I write the command "export DBT_PROFILES_DIR=./profiles" in terminal inside of VS Code?

**Comment by jfox-teine** [comment]
> Copied the profiles.yml out to the root directory, and changed the settings.json to be "DBT_PROFILES_DIR": "." and the error went away on opening VSCode, but I still can't preview a query. ![image](https://user-images.githubusercontent.com/97063651/208530337-2d5109d6-8944-4b9a-9547-e76d42cc3c0c.png)

I'm receiving this exact same error now. Was working fine yesterday.

**Comment by Bonnevie** [comment]
I'm getting a similar error message and my log keeps repeating
```
2023-01-18 15:37:15.427 [error] [innoverio.vscode-dbt-power-user] provider FAILED
2023-01-18 15:37:15.427 [error] undefined
```

**Comment by tomomonta** [comment]
I get a similar error to the above after having updated VSCode to 1.75.0

```
mainThreadExtensionService.ts:79 [[object Object]]Could not initialize Python bridge
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:701
deliver @ event.ts:908
fire @ event.ts:869
fire @ ipc.net.ts:671
Z.onmessage @ localProcessExtensionHost.ts:615
mainThreadExtensionService.ts:80 Error: Could not initialize Python bridge
	at DBTProject.<anonymous> (vscode-file://vscode-app/Users/tomo/.vscode/extensions/innoverio.vscode-dbt-power-user-0.11.3/dist/extension.js:7543:7)
	at Generator.next (<anonymous>)
	at fulfilled (vscode-file://vscode-app/Users/tomo/.vscode/extensions/innoverio.vscode-dbt-power-user-0.11.3/dist/extension.js:8859:23)
```

**Comment by tomomonta** [comment]
I "fixed" the error by `cd ..` into the folder, activating my conda env and starting vscode from that dir with `code .`

**Comment by paulfry-payroc** [comment]
not sure if it's of use to others, I managed to resolve this error my scenario by: 

* (temporarily) removing the use of 'env_var' in profiles.yml
*  manually verifying my dbt-core install was up to date
- my dbt-snowflake install was up to date, but dbt-core was slightly behind.

And I was running into this issue for both users on WSL (Ubuntu) and Mac.

**Comment by magnetar-star** [comment]
had the same problem, for me it was due to change python version environment 3.8 -> 3.11 and forgot to pip install dbt-core and dbt-snowflake

**Comment by darist** [comment]
Got the error:

```
Could not execute query, because the Python bridge has not been initalized. If the issue persists, please open a Github issue.
```

Fixed it by setting the absolute path to the dir with my profiles.yml in settings > dbt: Profiles Dir Override.

Then started getting 

```
AttributeError: 'NoneType' object has no attribute 'find_generate_macro_by_name'
```

May or may not have helped: Restarted extension host, upgraded to the latest version of dbt-core, dbt-bigquery using `pip install --upgrade`, restarted extension host again. Still saw the NoneType error.

Closed VSCode, opened it again. It works now.

**Comment by Jens1989** [comment]
still having this issue. Using anaconda environment with 

- python 3.9.16
- vscode 1.77.0
- dbt 0.21.1
dbt-bigquery 0.21.1
dbt-core 0.21.1
dbt-extractor 0.4.0
dbt-postgres  0.21.1
dbt-redshift 0.21.1
dbt-snowflake 0.21.1

![image](https://user-images.githubusercontent.com/21284247/230048107-a70053c5-89d7-4030-b674-bd93ba7412fe.png)

![image](https://user-images.githubusercontent.com/21284247/230048161-16cfc84d-ed0e-4620-9e8b-a00ea7c143b2.png)

I had vscode 1.9 which didn't work with dbt power user and python 3.10 before

**Comment by Jens1989** [comment]
> 

I had this resolved by using admin rights within the company I work for

**Comment by lllong33** [comment]
> Can you check Help > Toggle Developer Tools and check the console log.
> 
> If possible could you try to create a reproduction repo.

I also encountered the same problem, but it was successfully resolved after lowering from dbt-core 1.5.0b2 to 1.4.3;
In addition, I am curious about the debug operation of this debug plugin, can you recommend relevant demo

**Comment by Glenn9** [comment]
After testing, turning off SIP function on MacOS can solve this problem.

**Comment by sunapana2003** [comment]
I was able to fix it with the below video:
https://youtu.be/icKKQXUY2iQ

**Comment by lassebenni** [comment]
I faced this issue with `python3.10`, VSCode `1.18.1`, DBT Power User `v0.17.5`, dbt-core `1.5.6`. 

I could only resolve it by reverting to `python3.9`.

**Comment by ald0405** [comment]
> I faced this issue with `python3.10`, VSCode `1.18.1`, DBT Power User `v0.17.5`, dbt-core `1.5.6`.
> 
> I could only resolve it by reverting to `python3.9`.

Has anyone else confirmed that the issue is with the python version?

**Comment by geoHeil** [comment]
I have the same error on 3.11, DBT is detected I have set an absolute path but still face No file system provider found for resource 'query-preview in the logs and the same error. The host is a linux server (debian) with vscode running in the remote ssh session using dbt-duckdb

**Comment by geoHeil** [comment]
I could fix this by manually setting the global environment variable `DBT_PROFILES_DIR`. The setting within dbt power user for the profile path override seems to be ignored for me - even when passing an absolute directory there.
