### PR TITLE
chore: bump dbt-integration to 0.3.13 and release 0.64.6

### PR DESCRIPTION
**Pull request by ralphstodomingo**
## Release 0.64.6

Rolling release PR — the description is the running list of what this release carries.

### Bumps

- `@altimateai/dbt-integration` `^0.3.12` → `^0.3.13` (AltimateAI/altimate-dbt-integration#173, AltimateAI/altimate-dbt-integration#174)
- extension `0.64.5` → `0.64.6`

### Fixes carried

- **Play-button queries lost defer-to-production and the `graph` context in 0.64.5** (#2080). The library had moved query compilation onto the per-query private bridge, whose project never runs the full parse that merges the deferral state manifest and builds the flat graph. 0.3.13 compiles play-button queries on the parsed main bridge, with readiness decided atomically on the Python side and the private bridge kept as the fallback while the main one is re-initializing.

### Verification

Extension-level E2E (real VS Code + real ms-python, `@vscode/test-electron`, jaffle-shop on duckdb, dbt 1.12): defer-to-production configured against a state manifest whose `customers` lives in schema `prod`; executing `select * from {{ ref('customers') }}` via the play button:

| library | compiled relation on the play-button path |
|---|---|
| 0.3.12 (shipped in 0.64.5) | `"jaffle_shop"."main"."customers"` — local, defer ignored |
| 0.3.13 (this release) | `"jaffle_shop"."prod"."customers"` — state manifest respected |

Worth noting how silent the bug is: with the local `customers` still present, the 0.3.12 run *succeeded* — `executeSQL: Executed query …`, rows returned, no error, nothing in telemetry — against the wrong relation. The table above was captured with the local relation dropped so both resolutions fail at execution and log their compiled SQL.

The `{{ graph }}` half shares the mechanism (proven at the library level; on dbt <= 1.9 `manifest.flat_graph` is a plain empty dict until the full parse).

- **Fusion not detected when installed with pip into a venv** (#2018). `pip install --pre dbt` (Fusion 2.0 preview) is a binary-only package — no `dbt` python module, and the executable lands next to the interpreter it was installed into. The library only searched `~/.local/bin/dbt` and PATH; 0.3.13 looks next to the selected interpreter first, and validates that candidate via `--version` before using it as the command binary (a venv with dbt Core has Core's console script at the same path).

  Extension-level E2E (fusion mode, the pip-installed Fusion venv selected as interpreter, asserting on the env-change re-detection):

  | library | verdict after selecting the venv | command binary chosen |
  |---|---|---|
  | 0.3.12 (shipped in 0.64.5) | `dbt fusion cli was not found in any known location` | `~/.local/bin/dbt` (a dbt Cloud CLI here), selected on existence alone |
  | 0.3.13 (this release) | `dbt fusion cli detected at: <venv>/bin/dbt` | `<venv>/bin/dbt` |

  No extension-side change is required for the fix; the "Detect Python from terminal" probe still requiring `import dbt` in fusion mode is a separate, optional follow-up.

### Status

- [x] dbt-integration 0.3.13 published to npm (2026-09-16) → `package-lock.json` resolves 0.3.13 from the registry; extension E2E re-run against the published package (see below)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01UA5nH2ugGdXHckhkSvh5pb

## Summary by CodeRabbit

- **Chores**
  - Updated the extension to version 0.64.6.
  - Updated the dbt integration runtime dependency to version 0.3.13.

### CODE REVIEW

**Comment by ralphstodomingo** [comment]
## E2E against the published package

Re-ran both fix suites with `@altimateai/dbt-integration` **0.3.13 resolved from the npm registry** (no local link) in this branch's build — real VS Code + real ms-python via `@vscode/test-electron`:

| suite | result |
|---|---|
| play-button defer (#2080) — `select * from {{ ref('customers') }}` with defer-to-prod against a state manifest whose `customers` is in schema `prod` | compiled to `"jaffle_shop"."prod"."customers"` ✓ |
| fusion detection (#2018) — fusion mode, pip-installed Fusion venv selected as interpreter | `dbt fusion cli detected at: <venv>/bin/dbt` → `Using Fusion binary at: <venv>/bin/dbt` ✓ |

Lockfile: 0.3.13, registry-resolved; extension 0.64.6.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by ralphstodomingo** [comment]
## Release-candidate verification (head `b3a4c1a0`)

- 0 commits behind `master`.
- Clean install from the lockfile (`rm -rf node_modules && npm ci`) → `@altimateai/dbt-integration` **0.3.13** from the registry; `rsbuild` build green; bundle carries the three shipped fixes (scan skip, play-button compile placement, Fusion detection).
- Full extension-level E2E sweep on that build (real VS Code + real ms-python, `@vscode/test-electron`, jaffle-shop on duckdb, dbt 1.12):

| suite | result |
|---|---|
| bridge journeys — `runCurrentModel`, `testCurrentModel`, `compileCurrentModel` through the live bridge | 3/3 |
| scan-skip arc — healthy scan → dead bridge → skip (no NameError) → recovery, plus a process audit (one live bridge, nothing stale holding the duckdb) | 5/5 |
| play-button defer-to-prod (#2080) — `ref('customers')` compiles to `"jaffle_shop"."prod"."customers"` | 1/1 |
| Fusion detection (#2018) — pip-installed Fusion venv selected → `dbt fusion cli detected at: <venv>/bin/dbt`, used as the command binary | 1/1 |

CI: 25 pass / 3 skipped (release-publish jobs).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by ralphstodomingo** [comment]
## Regression angles for the 0.3.12 → 0.3.13 delta (run on this build)

The 0.3.13 delta moved play-button compilation onto the shared, parsed main bridge and changed the Fusion binary search. Angles exercised end to end (real VS Code + real ms-python), all on the clean `npm ci` build with the published 0.3.13:

| angle | outcome |
|---|---|
| **1. Genuine compilation error on the main bridge** (`ref('does_not_exist')`) | propagates, nothing executes, no defer-less retry on the private bridge; surfaces as a notification exactly as on 0.3.12 ✓ |
| **2. Play-button issued while a manifest rebuild is in flight** (model file touched, query fired immediately) | query waits behind the parse on the main bridge and still resolves defer (`"prod"."customers"`); the rebuild completes ✓ |
| **3. Dead main bridge** (interpreter switched to a dbt-less venv) → **recovery** (switched back) | dead: nothing executes, no error-level NameError (only the expected warn-level `getQuery` reclassification); recovered: re-init → re-parse → play-button compiles on the main bridge with defer again — the python-side parsed-readiness lifecycle holds through a real environment swap ✓ |
| **4. dbt Core venv selected while Fusion lives in `~/.local/bin`** (fusion mode) | Core's console script tried first and rejected by `--version` for both detection and binary selection; Fusion detected and used from `~/.local/bin/dbt` ✓ |

Not exercisable here, reasoned instead: cancelling a query cannot interrupt a main-bridge compilation (0.3.9's exact semantics; the private-bridge fallback path keeps kill-based cancellation); Windows path handling for the Fusion candidate is unit-tested; the Fusion `--version` validation adds one bounded (15s cap) process spawn per project init in fusion mode only. Core/cloud modes never touch the Fusion candidate code.

**Pre-existing residual surfaced by angle 4** (not a 0.3.13 regression, follow-up for 0.3.14): `initializeProject` validates only the interpreter-adjacent candidate — `~/.local/bin/dbt` is still selected on existence alone, and on a machine where that is the dbt Cloud CLI it becomes the "Fusion" command binary. Fix: apply the same `--version` validation to every path-based candidate.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Review by mdesmet — APPROVED** [review]
