### ISSUE TITLE
‘LoomRunnableConfig’ object has no attribute ‘project_name’

### ISSUE THREAD

**Issue by alangner** [AltimateAI/vscode-dbt-power-user#1224]
### Expected behavior

Extension should start (compile the project) without error

### Actual behavior

The following message is output as a project problem: “There is a problem in your dbt project. Compilation failed: ‘LoomRunnableConfig’ object has no attribute ‘project_name’”

### Steps To Reproduce

I am using project dependencies with dbt-loom.
Everything worked fine with dbt-power-user version 0.39.20, but broke with 0.40.0.(and 0.40.1).
The error occurs immediatly after starting VSCode and loading the extension.

### Operating System

Debian 11

### dbt version

1.7.3

### dbt Adapter

bigquery

### dbt Power User version

0.40.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
Pushed a fix in 0.40.2. @alangner Can you verify the fix?

**Comment by alangner** [comment]
Can confirm that it is fixed! 👍
